Implement changes from feedback #1
lucasiragusa/landingpermit_app pull request #8
Opened 2023-12-15 15:50 UTC by lucasiragusa

Installed packages, replaced os.path with pathlib, added docstrings, and generated docx output. Known bugs: poor table formatting in docx and potential infinite loop for countries with many flight series.

2023-12-15 15:56 UTC, lucasiragusa reviewed
Made the first push, could you please review?

2023-12-15 15:56 UTC, lucasiragusa commented on src/landingpermit_app.egg-info/SOURCES.txt
> +src/utils/file_helper.py
Not sure if this should be here?

2023-12-15 23:35 UTC, Zaubeerer requested changes
Hey @lucasiragusa, I have some minor suggestions to change before merging. 

Let me know if you have questions!

2023-12-15 23:35 UTC, Zaubeerer commented on data/.DS_Store
add to .gitignore and remove this file from the git repo, `git rm --cached data/.DS_Store` or similar should to the trick

2023-12-15 23:35 UTC, Zaubeerer commented on src/landingpermit_app.egg-info/PKG-INFO
> +Metadata-Version: 2.1
add to .gitignore and remove it from git, as described above

2023-12-15 23:35 UTC, Zaubeerer commented on src/lib/comparer.py
> +# A base ssim and an alt ssim and outputing only the files that changed.
Sounds good! We already have a follow-up issue, so we can merge this here as is

2023-12-15 23:35 UTC, Zaubeerer commented on src/lib/permit_generator.py
> +sys.path.append(str(Path(__file__).resolve().parent.parent))
nice one!

2023-12-15 23:35 UTC, Zaubeerer commented on src/lib/permit_generator.py
> +
Nice docstring! 

You don't have to add the types in the docstring, as we will rather add those as type annotations and then use sphinx autodocs to automatically get the types from the type annotations.

Don't worry if this is a bit abstract now, we will cover this in the next weeks :)

2023-12-15 23:35 UTC, Zaubeerer commented on src/models/airport.py
> +airport_data = pd.read_pickle('../data/industry/airport_data.pkl')
better also define this path with pathlib.

You can start with cfd (current file directory) by using `pathlib.Path(__file__)` ;-)

2023-12-22 15:40 UTC, lucasiragusa commented on data/.DS_Store
Added issue: https://github.com/lucasiragusa/landingpermit_app/issues/17

2023-12-22 15:42 UTC, lucasiragusa commented on src/landingpermit_app.egg-info/PKG-INFO
> +Metadata-Version: 2.1
Addressed in issue https://github.com/lucasiragusa/landingpermit_app/issues/17

2023-12-22 15:45 UTC, lucasiragusa commented on src/landingpermit_app.egg-info/SOURCES.txt
> +src/utils/file_helper.py
as per issue https://github.com/lucasiragusa/landingpermit_app/issues/17

2023-12-22 15:46 UTC, Zaubeerer approved these changes
looks good to me

2023-12-22 15:46 UTC, merged